// Per-make taxonomy. Key = canonical model (lowercase). Value = aliases-array.
// Volgorde binnen aliases doet ertoe: langere/specifieker eerst (Altea XL voor Altea).
// Trim-aliases (320i, e350) mappen naar parent model (3-serie, e-klasse).
//
// Spelling-variants: '3-serie', '3 serie', '3serie' allemaal acceptabel.
// Hyphens & spaces worden tijdens parsing genormaliseerd.

const TAXONOMY = {
  volkswagen: {
    "passat": ["passat"],
    "tiguan": ["tiguan"],
    "touareg": ["touareg"],
    "touran": ["touran"],
    "sharan": ["sharan"],
    "t-cross": ["t-cross", "t cross", "tcross"],
    "t-roc": ["t-roc", "t roc", "troc"],
    "arteon": ["arteon"],
    "amarok": ["amarok"],
    "caddy": ["caddy"],
    "transporter": ["transporter", "t5", "t6"],
    "crafter": ["crafter"],
    "jetta": ["jetta"],
    "eos": ["eos"],
    "scirocco": ["scirocco"],
    "beetle": ["beetle", "new beetle", "kever"],
    "fox": ["fox"],
    "lupo": ["lupo"],
    "up": ["up!", "up "],
    "id.3": ["id.3", "id 3", "id3"],
    "id.4": ["id.4", "id 4", "id4"],
    "id.5": ["id.5", "id 5", "id5"],
    "id.7": ["id.7", "id 7", "id7"],
    "id.buzz": ["id.buzz", "id buzz", "buzz"],
    "polo": ["polo"],
    "golf": ["golf", "golf plus", "golf variant", "golf gti", "golf gtd", "golf r"]
  },
  renault: {
    "twingo": ["twingo"],
    "clio": ["clio"],
    "captur": ["captur"],
    "kadjar": ["kadjar"],
    "scenic": ["scenic", "grand scenic"],
    "megane": ["megane", "mégane"],
    "kangoo": ["kangoo"],
    "master": ["master"],
    "trafic": ["trafic"],
    "espace": ["espace"],
    "koleos": ["koleos"],
    "talisman": ["talisman"],
    "zoe": ["zoe"],
    "laguna": ["laguna"],
    "modus": ["modus", "grand modus"],
    "twizy": ["twizy"],
    "arkana": ["arkana"],
    "austral": ["austral"]
  },
  kia: {
    "rio": ["rio"],
    "cee'd": ["cee'd", "ceed", "cee d", "cee'd sw", "ceed sw"],
    "sportage": ["sportage"],
    "niro": ["niro"],
    "picanto": ["picanto"],
    "sorento": ["sorento"],
    "soul": ["soul"],
    "venga": ["venga"],
    "stonic": ["stonic"],
    "optima": ["optima"],
    "carens": ["carens"],
    "ev6": ["ev6"],
    "ev9": ["ev9"],
    "xceed": ["xceed", "xceed sw"],
    "stinger": ["stinger"]
  },
  toyota: {
    "aygo": ["aygo", "aygo x"],
    "yaris": ["yaris", "yaris cross"],
    "corolla": ["corolla", "corolla touring", "corolla verso"],
    "prius": ["prius", "prius+", "prius plus"],
    "c-hr": ["c-hr", "chr", "c hr"],
    "rav4": ["rav4", "rav 4", "rav-4"],
    "auris": ["auris", "auris touring"],
    "avensis": ["avensis"],
    "hilux": ["hilux"],
    "proace": ["proace", "proace city", "proace verso"],
    "land cruiser": ["land cruiser", "landcruiser"],
    "verso": ["verso", "verso-s"],
    "urban cruiser": ["urban cruiser"],
    "bz4x": ["bz4x"],
    "mirai": ["mirai"],
    "highlander": ["highlander"]
  },
  audi: {
    "a1": ["a1"],
    "a3": ["a3", "a3 sportback", "a3 limousine"],
    "a4": ["a4", "a4 avant", "a4 allroad"],
    "a5": ["a5", "a5 sportback", "a5 coupe", "a5 cabriolet"],
    "a6": ["a6", "a6 avant", "a6 allroad"],
    "a7": ["a7", "a7 sportback"],
    "a8": ["a8"],
    "q2": ["q2"],
    "q3": ["q3", "q3 sportback"],
    "q4": ["q4", "q4 e-tron"],
    "q5": ["q5", "q5 sportback"],
    "q7": ["q7"],
    "q8": ["q8", "q8 e-tron"],
    "tt": ["tt", "tt rs", "tts"],
    "e-tron": ["e-tron", "etron"],
    "rs3": ["rs3", "rs 3"],
    "rs4": ["rs4", "rs 4"],
    "rs6": ["rs6", "rs 6"],
    "s3": ["s3"],
    "s4": ["s4"],
    "s5": ["s5"]
  },
  "mercedes-benz": {
    "a-klasse": ["a-klasse", "a klasse", "a180", "a 180", "a200", "a 200", "a220", "a 220", "a250", "a 250", "a160", "a 160", "a170", "a 170", "a190", "a 190", "a45", "a 45"],
    "b-klasse": ["b-klasse", "b klasse", "b150", "b 150", "b160", "b 160", "b170", "b 170", "b180", "b 180", "b200", "b 200", "b220", "b 220", "b250", "b 250"],
    "c-klasse": ["c-klasse", "c klasse", "c160", "c 160", "c180", "c 180", "c200", "c 200", "c220", "c 220", "c230", "c 230", "c240", "c 240", "c250", "c 250", "c270", "c 270", "c280", "c 280", "c300", "c 300", "c320", "c 320", "c350", "c 350", "c43", "c 43", "c63", "c 63"],
    "e-klasse": ["e-klasse", "e klasse", "e200", "e 200", "e220", "e 220", "e240", "e 240", "e250", "e 250", "e260", "e 260", "e270", "e 270", "e280", "e 280", "e300", "e 300", "e320", "e 320", "e350", "e 350", "e400", "e 400", "e420", "e 420", "e500", "e 500", "e55", "e 55", "e63", "e 63"],
    "s-klasse": ["s-klasse", "s klasse", "s280", "s 280", "s300", "s 300", "s320", "s 320", "s350", "s 350", "s400", "s 400", "s420", "s 420", "s430", "s 430", "s500", "s 500", "s550", "s 550", "s560", "s 560", "s600", "s 600", "s63", "s 63"],
    "cla": ["cla", "cla 180", "cla 200", "cla 220", "cla 250", "cla 45"],
    "cls": ["cls", "cls 250", "cls 350", "cls 400", "cls 500"],
    "gla": ["gla", "gla 180", "gla 200", "gla 220", "gla 250", "gla 45"],
    "glb": ["glb"],
    "glc": ["glc", "glc 200", "glc 220", "glc 250", "glc 300", "glc 350", "glc 43", "glc 63"],
    "gle": ["gle", "gle 250", "gle 300", "gle 350", "gle 400", "gle 450", "gle 500"],
    "gls": ["gls", "gls 350", "gls 400", "gls 500"],
    "ml": ["ml", "ml 280", "ml 300", "ml 320", "ml 350", "ml 400", "ml 500"],
    "g-klasse": ["g-klasse", "g klasse", "g 350", "g 400", "g 500", "g 63"],
    "vito": ["vito"],
    "vaneo": ["vaneo"],
    "citan": ["citan"],
    "sprinter": ["sprinter"],
    "v-klasse": ["v-klasse", "v klasse", "viano"],
    "eqa": ["eqa"],
    "eqb": ["eqb"],
    "eqc": ["eqc"],
    "eqe": ["eqe"],
    "eqs": ["eqs"],
    "slk": ["slk", "slk 200", "slk 230", "slk 350"],
    "sl": ["sl", "sl 350", "sl 500"],
    "amg gt": ["amg gt"]
  },
  bmw: {
    "1-serie": ["1-serie", "1 serie", "1serie", "1er", "1 reihe", "1er reihe", "114", "116", "118", "120", "123", "125", "128", "130", "135", "m140", "m1"],
    "2-serie": ["2-serie", "2 serie", "2serie", "2er", "2 reihe", "2er reihe", "216", "218", "220", "225", "228", "230", "235", "240", "m235", "m240", "m2"],
    "3-serie": ["3-serie", "3 serie", "3serie", "3er", "3 reihe", "3er reihe", "315", "316", "318", "320", "323", "325", "328", "330", "335", "340", "318i", "318d", "320i", "320d", "320e", "325i", "325d", "330i", "330d", "330e", "335i", "335d", "m340", "m3"],
    "4-serie": ["4-serie", "4 serie", "4serie", "4er", "4 reihe", "4er reihe", "418", "420", "425", "428", "430", "435", "440", "m440", "m4"],
    "5-serie": ["5-serie", "5 serie", "5serie", "5er", "5 reihe", "5er reihe", "518", "520", "523", "525", "528", "530", "535", "540", "545", "550", "520i", "520d", "525i", "525d", "530i", "530d", "530e", "535i", "535d", "540i", "545i", "550i", "m550", "m5"],
    "6-serie": ["6-serie", "6 serie", "6serie", "6er", "6 reihe", "6er reihe", "630", "635", "640", "645", "650", "m6"],
    "7-serie": ["7-serie", "7 serie", "7serie", "7er", "7 reihe", "7er reihe", "725", "728", "730", "735", "740", "745", "750", "760"],
    "8-serie": ["8-serie", "8 serie", "8serie", "8er", "8 reihe", "830", "840", "850", "m8"],
    "i3": ["i3"],
    "i4": ["i4"],
    "i5": ["i5"],
    "i7": ["i7"],
    "i8": ["i8"],
    "ix": ["ix "],
    "ix1": ["ix1"],
    "ix3": ["ix3"],
    "x1": ["x1"],
    "x2": ["x2"],
    "x3": ["x3", "x3 m"],
    "x4": ["x4"],
    "x5": ["x5", "x5 m"],
    "x6": ["x6"],
    "x7": ["x7"],
    "z3": ["z3"],
    "z4": ["z4"]
  },
  seat: {
    "altea": ["altea xl", "altea freetrack", "altea"],
    "leon": ["leon st", "leon sc", "leon cupra", "leon"],
    "ibiza": ["ibiza st", "ibiza"],
    "toledo": ["toledo"],
    "cordoba": ["cordoba"],
    "arosa": ["arosa"],
    "mii": ["mii"],
    "ateca": ["ateca"],
    "arona": ["arona"],
    "tarraco": ["tarraco"],
    "alhambra": ["alhambra"],
    "exeo": ["exeo"]
  },
  ford: {
    "fiesta": ["fiesta"],
    "focus": ["focus"],
    "mondeo": ["mondeo"],
    "kuga": ["kuga"],
    "ecosport": ["ecosport", "eco sport"],
    "puma": ["puma"],
    "c-max": ["c-max", "c max", "cmax"],
    "s-max": ["s-max", "s max", "smax"],
    "galaxy": ["galaxy"],
    "ranger": ["ranger"],
    "transit custom": ["transit custom"],
    "transit connect": ["transit connect", "tourneo connect"],
    "transit": ["transit"],
    "tourneo": ["tourneo", "tourneo courier", "tourneo custom"],
    "ka": ["ka+", "ka "],
    "mustang": ["mustang", "mustang mach-e", "mach-e"],
    "explorer": ["explorer"],
    "edge": ["edge"]
  },
  nissan: {
    "micra": ["micra"],
    "note": ["note"],
    "leaf": ["leaf"],
    "juke": ["juke"],
    "qashqai": ["qashqai"],
    "x-trail": ["x-trail", "x trail", "xtrail"],
    "navara": ["navara"],
    "primera": ["primera"],
    "almera": ["almera"],
    "pulsar": ["pulsar"],
    "ariya": ["ariya"],
    "300zx": ["300zx"],
    "370z": ["370z"],
    "patrol": ["patrol"],
    "pathfinder": ["pathfinder"],
    "murano": ["murano"]
  },
  peugeot: {
    "108": ["108"],
    "208": ["208"],
    "308": ["308"],
    "408": ["408"],
    "508": ["508"],
    "2008": ["2008"],
    "3008": ["3008"],
    "5008": ["5008"],
    "206": ["206"],
    "207": ["207"],
    "807": ["807"],
    "partner": ["partner"],
    "expert": ["expert"],
    "boxer": ["boxer"],
    "rifter": ["rifter"],
    "traveller": ["traveller"]
  },
  opel: {
    "corsa": ["corsa"],
    "astra": ["astra"],
    "insignia": ["insignia"],
    "mokka": ["mokka", "mokka x"],
    "crossland": ["crossland", "crossland x"],
    "grandland": ["grandland", "grandland x"],
    "zafira": ["zafira"],
    "meriva": ["meriva"],
    "vivaro": ["vivaro"],
    "movano": ["movano"],
    "combo": ["combo"],
    "antara": ["antara"],
    "agila": ["agila"],
    "adam": ["adam"],
    "karl": ["karl"],
    "ampera": ["ampera", "ampera-e"]
  },
  citroen: {
    "c1": ["c1"],
    "c2": ["c2"],
    "c3": ["c3 picasso", "c3 aircross", "c3"],
    "c4": ["c4 picasso", "c4 cactus", "c4 grand picasso", "c4 spacetourer", "c4"],
    "c5": ["c5 aircross", "c5 x", "c5"],
    "c6": ["c6"],
    "c-elysee": ["c-elysee", "c elysee"],
    "c-zero": ["c-zero", "c zero"],
    "berlingo": ["berlingo"],
    "jumpy": ["jumpy"],
    "jumper": ["jumper"],
    "spacetourer": ["spacetourer"],
    "ds3": ["ds3"],
    "ds4": ["ds4"],
    "ds5": ["ds5"],
    "saxo": ["saxo"],
    "xsara": ["xsara"],
    "xantia": ["xantia"]
  },
  hyundai: {
    "i10": ["i10"],
    "i20": ["i20"],
    "i30": ["i30"],
    "i40": ["i40"],
    "kona": ["kona"],
    "tucson": ["tucson"],
    "santa fe": ["santa fe", "santafe"],
    "ix35": ["ix35"],
    "ix20": ["ix20"],
    "getz": ["getz"],
    "accent": ["accent"],
    "matrix": ["matrix"],
    "ioniq": ["ioniq", "ioniq 5", "ioniq 6"],
    "bayon": ["bayon"],
    "nexo": ["nexo"]
  },
  mazda: {
    "mazda2": ["mazda2", "mazda 2"],
    "mazda3": ["mazda3", "mazda 3"],
    "mazda5": ["mazda5", "mazda 5"],
    "mazda6": ["mazda6", "mazda 6"],
    "cx-3": ["cx-3", "cx 3"],
    "cx-30": ["cx-30", "cx 30"],
    "cx-5": ["cx-5", "cx 5"],
    "cx-7": ["cx-7", "cx 7"],
    "cx-9": ["cx-9", "cx 9"],
    "cx-60": ["cx-60", "cx 60"],
    "mx-30": ["mx-30", "mx 30"],
    "mx-5": ["mx-5", "mx 5", "miata"],
    "rx-8": ["rx-8", "rx 8"]
  },
  skoda: {
    "fabia": ["fabia"],
    "octavia": ["octavia"],
    "superb": ["superb"],
    "kodiaq": ["kodiaq"],
    "kamiq": ["kamiq"],
    "karoq": ["karoq"],
    "scala": ["scala"],
    "rapid": ["rapid"],
    "yeti": ["yeti"],
    "roomster": ["roomster"],
    "citigo": ["citigo"],
    "enyaq": ["enyaq"]
  },
  fiat: {
    "500": ["500l", "500x", "500c", "500"],
    "panda": ["panda"],
    "punto": ["punto", "grande punto"],
    "tipo": ["tipo"],
    "doblo": ["doblo"],
    "ducato": ["ducato"],
    "fiorino": ["fiorino"],
    "qubo": ["qubo"],
    "bravo": ["bravo"],
    "stilo": ["stilo"],
    "freemont": ["freemont"]
  },
  volvo: {
    "xc40": ["xc40", "xc 40"],
    "xc60": ["xc60", "xc 60"],
    "xc70": ["xc70", "xc 70"],
    "xc90": ["xc90", "xc 90"],
    "v40": ["v40", "v 40"],
    "v50": ["v50", "v 50"],
    "v60": ["v60", "v 60"],
    "v70": ["v70", "v 70"],
    "v90": ["v90", "v 90"],
    "s40": ["s40", "s 40"],
    "s60": ["s60", "s 60"],
    "s80": ["s80", "s 80"],
    "s90": ["s90", "s 90"],
    "c30": ["c30", "c 30"],
    "c70": ["c70", "c 70"],
    "ex30": ["ex30", "ex 30"],
    "ex40": ["ex40", "ex 40"],
    "ex90": ["ex90", "ex 90"],
    "amazon": ["amazon"]
  },
  tesla: {
    "model s": ["model s"],
    "model 3": ["model 3"],
    "model x": ["model x"],
    "model y": ["model y"],
    "roadster": ["roadster"],
    "cybertruck": ["cybertruck"]
  },
  mini: {
    "cooper": ["cooper s", "cooper d", "cooper se", "cooper"],
    "one": ["one"],
    "clubman": ["clubman"],
    "countryman": ["countryman"],
    "paceman": ["paceman"],
    "cabrio": ["cabrio", "cabriolet"],
    "coupe": ["coupe"],
    "roadster": ["roadster"]
  },
  porsche: {
    "911": ["911"],
    "718": ["718", "718 boxster", "718 cayman"],
    "boxster": ["boxster"],
    "cayman": ["cayman"],
    "cayenne": ["cayenne"],
    "macan": ["macan"],
    "panamera": ["panamera"],
    "taycan": ["taycan"]
  },
  suzuki: {
    "swift": ["swift"],
    "vitara": ["vitara", "grand vitara"],
    "ignis": ["ignis"],
    "celerio": ["celerio"],
    "baleno": ["baleno"],
    "splash": ["splash"],
    "alto": ["alto"],
    "jimny": ["jimny"],
    "sx4": ["sx4", "sx4 s-cross", "s-cross"],
    "across": ["across"],
    "swace": ["swace"]
  },
  mitsubishi: {
    "asx": ["asx"],
    "outlander": ["outlander"],
    "eclipse cross": ["eclipse cross", "eclipse"],
    "space star": ["space star", "spacestar"],
    "colt": ["colt"],
    "lancer": ["lancer"],
    "l200": ["l200", "l 200"],
    "pajero": ["pajero"],
    "i-miev": ["i-miev", "imiev"]
  },
  "land rover": {
    "defender": ["defender"],
    "discovery": ["discovery", "discovery sport"],
    "range rover": ["range rover", "range rover sport", "range rover evoque", "range rover velar"],
    "evoque": ["evoque"],
    "velar": ["velar"],
    "freelander": ["freelander"]
  },
  jaguar: {
    "xe": ["xe"],
    "xf": ["xf"],
    "xj": ["xj"],
    "xk": ["xk"],
    "f-pace": ["f-pace", "f pace"],
    "e-pace": ["e-pace", "e pace"],
    "i-pace": ["i-pace", "i pace"],
    "f-type": ["f-type", "f type"],
    "s-type": ["s-type", "s type"]
  },
  jeep: {
    "renegade": ["renegade"],
    "compass": ["compass"],
    "cherokee": ["cherokee", "grand cherokee"],
    "wrangler": ["wrangler"],
    "avenger": ["avenger"],
    "commander": ["commander"],
    "patriot": ["patriot"]
  },
  "alfa romeo": {
    "giulia": ["giulia", "giulietta"],
    "stelvio": ["stelvio"],
    "mito": ["mito"],
    "tonale": ["tonale"],
    "156": ["156"],
    "159": ["159"],
    "147": ["147"],
    "brera": ["brera"],
    "spider": ["spider"]
  },
  dacia: {
    "sandero": ["sandero", "sandero stepway"],
    "duster": ["duster"],
    "logan": ["logan", "logan mcv"],
    "lodgy": ["lodgy"],
    "dokker": ["dokker"],
    "jogger": ["jogger"],
    "spring": ["spring"]
  },
  smart: {
    "fortwo": ["fortwo", "for two"],
    "forfour": ["forfour", "for four"],
    "roadster": ["roadster"],
    "#1": ["#1", "smart 1"],
    "#3": ["#3", "smart 3"]
  },
  lexus: {
    "ct": ["ct200h", "ct 200h", "ct"],
    "is": ["is300h", "is 300h", "is250", "is 250", "is"],
    "es": ["es"],
    "ls": ["ls"],
    "gs": ["gs"],
    "rc": ["rc"],
    "lc": ["lc"],
    "nx": ["nx300h", "nx 300h", "nx450h", "nx 450h", "nx"],
    "rx": ["rx450h", "rx 450h", "rx500h", "rx 500h", "rx"],
    "ux": ["ux250h", "ux 250h", "ux300e", "ux 300e", "ux"],
    "lx": ["lx"],
    "lbx": ["lbx"]
  }
}

module.exports = { TAXONOMY }
